// +build ignore
// +build !windows

package main

import (
	"bytes"
	"fmt"
	"io/ioutil"
	"log"
	"os"
	"os/exec"
	"strings"
)

var inputs = []string{
	`$`,
	`$$`,
	`$$$`,
	`$$$$`,
	`$$$$$`,
	`$ $`,
	`$ $ $`,
	`$$ $$`,
	`$$ $ $$`,
	`$\ $`,
	`$\$$`,
	`$$\$`,
	`$$\$$$`,
	`$$ \$$`,
	`$$ \$$ $$`,
	`$$ \$\$ $$`,
	`$\$$$`,
	`$\$$$$`,
	`$$ \$ $$`,
	`$$ $x$ $$`,
	`$x$ $x$ $$`,
	`$x$`,
	`$$x$`,
	`$x$$`,
	`$x$x$`,
	`$x$$x$`,
	`$x$x$x$`,
	`x$$$$`,
	`$x$$$`,
	`$$x$$`,
	`$$$x$`,
	`$$$$x`,
	`$x$$x$$`,
	`$$x$x$$`,
	`$$x$$x$`,
	`$x _k y_ k$`,
	`$x$x`,
	`$x $x`,
	`$x $ x`,
	`$x$ x`,
	`$ x$x`,
	`$$x$$x`,
	`$$x $$x`,
	`$$x $$ x`,
	`$$x$$ x`,
	`$$ x$$x`,
	`x$$x$$x`,
	`    $$x$$`,
	"$x\n$",
	"$x\nx$",
	"$$x\n$$",
	"$$x\n\n$$",
	"$$\nx\n$$",
	"$$\nx\nx\nx\n$$",
	"$$\nx\nx\n\n$$",
	"$$\n\nx\nx\n$$",
	"$$\n\nx\n\n$$",
	"$`$`",
	"`$`$",
	`<a href="$">$`,
	`$<a href="$">$`,
	`<http://a.b.$c>$`,
	"[link]: $x$\n[link]",
	`a[$b$](c)`,
	`$a[b$](c)`,
	`[$[]$](b)`,
	`[$]$](b)`,
	`[a]($b$)`,
	`[a$b](c$)`,
	"> $$x\n$$",
	" - a\n\n   $x$",
	"# $x$",
	"$x$\n---",
}

func normalize(s string) string {
	s = strings.TrimSpace(s)
	s = strings.ReplaceAll(s, " id=\"x\"", "")
	s = strings.ReplaceAll(s, " class=\"uri\"", "")
	s = strings.ReplaceAll(s, "&quot;", "\"")
	s = strings.ReplaceAll(s, "<li><p>", "<li>\n<p>")
	s = strings.ReplaceAll(s, "</p></li>", "</p>\n</li>")
	return s
}

func main() {
	if len(os.Args) > 0 && os.Args[1] == "windows" {
		log.Println("gen.go: warning: gen.go requires a bash shell and will probably fail on windows!")
	}
	var b bytes.Buffer
	var err error
	b.WriteString("// Code generated by gen.go. DO NOT EDIT.\n\n")
	b.WriteString("package qjskatex\n\n")
	b.WriteString("var tests = []struct {\n\tin, out string\n}{\n")
	for _, in := range inputs {
		var out bytes.Buffer
		cmd := exec.Command("pandoc", "--katex", "--filter", "./katex/filter.js")
		cmd.Stdin = strings.NewReader(in)
		cmd.Stdout = &out
		err = cmd.Run()
		if err != nil {
			log.Fatalf("gen.go: error: %v\n", err)
			break
		}
		s := fmt.Sprintf("\t{%q, %q},\n", in, normalize(out.String()))
		b.WriteString(s)
	}
	b.WriteString("}\n")
	ioutil.WriteFile("gen_test.go", b.Bytes(), 0644)
}
